name: build
on:
  workflow_dispatch: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate tarball from image
      run: |
        docker pull asia-south1-docker.pkg.dev/civic-replica-421010/example/api.go:latest
        docker save -o vuln-image.tar asia-south1-docker.pkg.dev/civic-replica-421010/example/api.go:latest

    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@master
      with:
        input: /github/workspace/vuln-image.tar
        severity: 'CRITICAL,HIGH'