name: build
on:
  workflow_dispatch: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ vars.PROJECT_ID}}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Auth to repo first time
      run:  gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Generate tarball from image
      run: |
        docker pull asia-south1-docker.pkg.dev/${{ vars.PROJECT_ID}}/example/api.go:latest
        docker save -o ${GITHUB_WORKSPACE}/vuln-image.tar asia-south1-docker.pkg.dev/${{ vars.PROJECT_ID}}/example/api.go:latest

    - name: List workspace files
      run: ls -la ${GITHUB_WORKSPACE}

    - name: Inspect tarball
      run: file ${GITHUB_WORKSPACE}/vuln-image.tar


    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@master
      with:
        input: ${GITHUB_WORKSPACE}/vuln-image.tar
        severity: 'CRITICAL,HIGH'